# Generated by Django 3.1.4 on 2022-05-18 09:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointSale',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название торговой точки')),
            ],
            options={
                'verbose_name': 'Торговая точка',
                'verbose_name_plural': 'Торговые точки',
                'db_table': 'point_sale_db',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Имя работника')),
                ('number_phone', models.CharField(max_length=255, verbose_name='Номер телефона работника')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
                'db_table': 'worker_db',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_visit', models.DateField(default=django.utils.timezone.now, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('point_sale_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='visits.pointsale')),
            ],
            options={
                'verbose_name': 'Визит',
                'verbose_name_plural': 'Визиты',
                'db_table': 'visit_db',
            },
        ),
        migrations.AddField(
            model_name='pointsale',
            name='worker_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='visits.worker'),
        ),
    ]
