# Generated by Django 4.0.4 on 2022-05-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date_visit',
            field=models.DateTimeField(default=None, null=True, verbose_name='Дата и время визита'),
        ),
    ]
